spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pre_project_2_4
    username: postgres
    password: agroycg592:ggg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true

app:
  password-pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$