spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pre_project_2_2
    username: postgres
    password: agroycg592:ggg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  car-service:
    max-count-cars: 6
    sort-on-fields: id, model, price
  income-api-service:
    api-url: https://66055cd12ca9478ea1801f2e.mockapi.io/api/users/income

loan:
  minimal-income: 40000
  minimal-car-price: 1000000
  months-to-compute: 6
  car-price-part-to-compute: 0.3
