name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  push-compose:
    name: push docker-compose.yml to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: "194.87.94.5"
          username: "lev"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/project"