spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pre_project_2_2
    username: postgres
    password: agroycg592:ggg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  car-service:
    max-count-cars: 6
    sort-on-fields: id, model, price
